---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-resource-driver
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: intel-gpu-resource-driver
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cdi:
      staticPath: /var/cdi/static
      dynamicPath: /var/cdi/dynamic
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DeviceClass
              name: gpu.intel.com
            patch: |-
              - op: replace
                path: /apiVersion
                value: resource.k8s.io/v1
