---
apiVersion: v1
kind: Namespace
metadata:
  name: not-used
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    resource.kubernetes.io/admin-access: "true"
    volsync.backube/privileged-movers: "true"
