---
ingress:
  - hostname: turbo.ac
    originRequest:
      originServerName: turbo.ac
    service: https://envoy-external.network.svc.cluster.local:443
  - hostname: plex.turbo.ac
    service: http://plex.default.svc.cluster.local:32400
    originRequest:
      originServerName: external.turbo.ac
  - hostname: "*.turbo.ac"
    originRequest:
      originServerName: external.turbo.ac
    service: https://envoy-external.network.svc.cluster.local:443
  - service: http_status:404
