---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
spec:
  chartRef:
    kind: OCIRepository
    name: fluent-bit
  maxHistory: 2
  interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    config:
      service: |-
        [SERVICE]
          daemon off
          flush {{ .Values.flush }}
          log_level {{ .Values.logLevel }}
          parsers_file /fluent-bit/etc/parsers.conf
          parsers_file /fluent-bit/etc/conf/custom_parsers.conf
          http_Server on
          http_Listen 0.0.0.0
          http_port {{ .Values.metricsPort }}
          Health_check on

      inputs: |-
        [INPUT]
          name tail
          alias kubernetes
          path /var/log/containers/*.log
          parser containerd
          tag kubernetes.*
          mem_buf_limit 5MB
          skip_empty_lines on
          skip_long_lines on

      filters: |-
        [FILTER]
          name kubernetes
          match kubernetes.*
          kube_url https://kubernetes.default.svc:443
          kube_ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          kube_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
          kube_tag_prefix kubernetes.var.log.containers.
          merge_log on
          merge_log_key log_processed
          merge_log_trim on
          k8s-logging.parser on
          k8s-Logging.exclude off
          labels on
          annotations off

      outputs: |-
        [OUTPUT]
          Name loki
          Match kubernetes.*
          host loki-headless.observability.svc.cluster.local
          port 3100
          line_format json
          labels job=fluent-bit, namespace=$kubernetes['namespace_name'], app=$kubernetes['labels']['app.kubernetes.io/name']
          structured_metadata $kubernetes['pod_name'], host=$kubernetes['host']
          compress gzip
